# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a79b4840da23c859d4e4c7d4d0ec464647108ded43e3b24ed6eac4b27422267feed32de6ad805218fe840b763f28dc05c2a39daac1d28c3d0f89dbd8a621ea3

test:
  secret_key_base: 5324e4b63e140b715da26a803efab995cf00e6bd2da414579486b785d28ecfd1e100e97601bb14e44226972568175a46422e718c1543d314cc0b6b64c619ae9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
